# Generated by Django 4.1.4 on 2022-12-12 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_quotationitem_email_remove_quotationitem_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='quot_status',
            field=models.CharField(choices=[('No Status', 'No Status'), ('Spec Confirmed', 'Spec Confirmed'), ('Active', 'Active'), ('On-hold', 'On-hold'), ('Order Confirmed', 'Order Confirmed')], default='no', max_length=50),
        ),
    ]
