# Generated by Django 4.1.4 on 2022-12-13 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_quotation_quot_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='quot_status',
            field=models.CharField(choices=[('No Status', 'No Status'), ('Spec Confirmed', 'Spec Confirmed'), ('Active', 'Active'), ('On-hold', 'On-hold'), ('Order Confirmed', 'Order Confirmed')], default='No Status', max_length=50),
        ),
    ]
